/**
 * Validates the question bank and regenerates content/questions.md from it.
 *
 * The TypeScript data is the single source of truth. The markdown is a
 * generated review surface, so the two cannot drift apart. Run with --check
 * to validate without writing.
 *
 * Usage:
 *   npm run questions:check
 *   npm run questions:build
 */
import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { dimensions, questions, questionsFor } from '../src/data/assessment.js';
import { LEVEL_NAMES, LEVELS } from '../src/data/types.js';
import type { Question } from '../src/data/types.js';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = resolve(ROOT, 'content/questions.md');

const MIN_PER_DIMENSION = 5;
const MAX_PER_DIMENSION = 10;

const errors: string[] = [];
const warnings: string[] = [];

/** Every human-facing string on a question, for the house-style check. */
const proseOf = (q: Question): string[] => [
  q.text,
  q.why,
  ...LEVELS.map((l) => q.anchors[l]),
  q.conditions[0].action,
  q.conditions[1].action,
];

function validate(): void {
  const seen = new Set<string>();
  for (const q of questions) {
    if (seen.has(q.id)) errors.push(`Duplicate question id: ${q.id}`);
    seen.add(q.id);

    if (!q.id.startsWith(`${q.dimension}-`)) {
      errors.push(`${q.id}: id prefix does not match dimension "${q.dimension}"`);
    }

    for (const level of LEVELS) {
      if (!q.anchors[level]?.trim()) {
        errors.push(`${q.id}: missing anchor for level ${level} (${LEVEL_NAMES[level]})`);
      }
    }

    for (const level of [0, 1] as const) {
      const c = q.conditions[level];
      if (!c?.action?.trim()) errors.push(`${q.id}: missing condition action for level ${level}`);
      if (!c?.mergeKey?.trim()) errors.push(`${q.id}: missing mergeKey for level ${level}`);
    }

    // House style. An em-dash in content is a bug, not a preference.
    for (const text of proseOf(q)) {
      if (text.includes('—')) errors.push(`${q.id}: em-dash in content: "${text.slice(0, 60)}..."`);
    }

    if (q.source && !/^https:\/\//.test(q.source.url)) {
      errors.push(`${q.id}: source url is not https: ${q.source.url}`);
    }
  }

  for (const d of dimensions) {
    const qs = questionsFor(d.id);
    if (qs.length < MIN_PER_DIMENSION || qs.length > MAX_PER_DIMENSION) {
      errors.push(
        `${d.name}: ${qs.length} questions, outside the agreed range of ${MIN_PER_DIMENSION} to ${MAX_PER_DIMENSION}`,
      );
    }
    const critical = qs.filter((q) => q.pilotCritical).length;
    // No dimension should be able to monopolise the no-go logic on its own.
    if (critical < 3 || critical > 4) {
      warnings.push(
        `${d.name}: ${critical} pilot-critical questions, outside the intended 3 to 4 balance`,
      );
    }
  }
}

function generate(): string {
  const total = questions.length;
  const totalCritical = questions.filter((q) => q.pilotCritical).length;

  const out: string[] = [];
  out.push('# CARA question bank');
  out.push('');
  out.push(
    '> Generated from `src/data/` by `npm run questions:build`. Do not edit this file by hand,',
  );
  out.push('> your changes will be overwritten. Edit the TypeScript and regenerate.');
  out.push('');
  out.push(
    `${total} questions across ${dimensions.length} dimensions, of which ${totalCritical} are pilot-critical.`,
  );
  out.push('');
  out.push('Levels: 0 Not ready, 1 Emerging, 2 Ready, 3 Scalable.');
  out.push('');
  out.push('A **pilot-critical** question scored Not ready forces its whole dimension to Not ready,');
  out.push('and therefore produces a no-go. Any other question scored Not ready caps its dimension at');
  out.push('Emerging. Amber never blocks a pilot, it generates a launch condition.');
  out.push('');
  out.push('| Dimension | Questions | Pilot-critical |');
  out.push('|---|---|---|');
  for (const d of dimensions) {
    const qs = questionsFor(d.id);
    out.push(`| ${d.number}. ${d.name} | ${qs.length} | ${qs.filter((q) => q.pilotCritical).length} |`);
  }
  out.push(`| **Total** | **${total}** | **${totalCritical}** |`);
  out.push('');

  for (const d of dimensions) {
    out.push('---');
    out.push('');
    out.push(`## ${d.number}. ${d.name}`);
    out.push('');
    out.push(`*${d.premise}*`);
    out.push('');

    for (const q of questionsFor(d.id)) {
      out.push(`### ${q.id}${q.pilotCritical ? ' · pilot-critical' : ''}`);
      out.push('');
      out.push(`**${q.text}**`);
      out.push('');
      out.push(`${q.why}`);
      out.push('');
      out.push('| Level | You know it is this when |');
      out.push('|---|---|');
      for (const level of LEVELS) {
        out.push(`| ${LEVEL_NAMES[level]} | ${q.anchors[level]} |`);
      }
      out.push('');
      for (const level of [0, 1] as const) {
        const c = q.conditions[level];
        out.push(
          `- **If ${LEVEL_NAMES[level]}:** ${c.action} *(${c.owner}, ${c.timing})*`,
        );
      }
      if (q.source) {
        out.push(`- Source: [${q.source.label}](${q.source.url})`);
      }
      out.push('');
    }
  }

  return out.join('\n');
}

validate();

for (const w of warnings) console.warn(`warning  ${w}`);

if (errors.length) {
  for (const e of errors) console.error(`error    ${e}`);
  console.error(`\n${errors.length} error(s). Question bank is invalid.`);
  process.exit(1);
}

const checkOnly = process.argv.includes('--check');
if (checkOnly) {
  console.log(
    `Question bank valid: ${questions.length} questions, ${questions.filter((q) => q.pilotCritical).length} pilot-critical.`,
  );
} else {
  writeFileSync(OUT, `${generate()}\n`, 'utf8');
  console.log(`Wrote ${OUT}`);
  console.log(
    `${questions.length} questions, ${questions.filter((q) => q.pilotCritical).length} pilot-critical.`,
  );
}
